# .travis.yml development advice: check your changes at
# https://config.travis-ci.com/explore
os: linux
dist: bionic
language: node_js
branches:
  except:
    - /^greenkeeper.*/

stages:
  - name: test
    if: type IN (push, pull_request, api)
  - name: cron
    if: type IN (cron, api)

# Test against Long Term Support (LTS) releases in a "current", "active", and
# "maintenance" status: https://nodejs.org/en/about/releases/
node_js:
  - 14
  - 12
  - 10
install:
  - npm ci  # install from package-lock.json
script:
  - npm run lint
  - travis_retry npm test
after_success:
  - npm install -g codecov
  - npm run codecov

jobs:
  include:
    - name: deps:npm-audit
      stage: cron
      install:
        - npm ci --production
      script:
        # This audit will fail for moderate/high/critical and exclude low
        - npm audit --production --audit-level=moderate
      after_success:
        - echo "package-lock.json is considered at least moderately secure according to a npm audit."
      after_failure:
        - echo "package-lock.json contain a package with a moderate or worse vulnerability!"
        - echo "Running 'npm audit fix --production' could fix the vulnerability. Let's try..."
        - npm audit fix --production
